// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    defaultPoint: string
    label: string
    range: string
    scale: string
}
export const cssExports: CssExports
export default cssExports
