// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    item: string
    label: string
    radio: string
    thumb: string
    wrap: string
}
export const cssExports: CssExports
export default cssExports
