// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    active: string
    checkbox: string
    checkboxLeft: string
    label: string
    labels: string
    thumb: string
    wrap: string
}
export const cssExports: CssExports
export default cssExports
