// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    app: string
    canvas: string
    canvasWrap: string
    h2: string
}
export const cssExports: CssExports
export default cssExports
