// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    app: string
    applyButton: string
    canvas: string
    canvasWrap: string
    generalActions: string
    statusText: string
}
export const cssExports: CssExports
export default cssExports
