// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    childContainer: string
    container: string
    wrap: string
}
export const cssExports: CssExports
export default cssExports
