// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    active: string
    icon: string
    isDefaultPoint: string
    originalInput: string
    wrap: string
}
export const cssExports: CssExports
export default cssExports
